from bs4 import BeautifulSoup
from docx import Document

with open("D:\Agentic_AI\Projects\Document_Reader\Webpage\Chats\Flat_MMR.html", "r", encoding="utf-8") as f:
    soup = BeautifulSoup(f, "html.parser")

user_msgs = soup.find_all("div", class_="chat-bubble user-msg")
bot_msgs = soup.find_all("div", class_="chat-bubble bot-msg")

assert len(user_msgs) == len(bot_msgs), "Mismatch in number of questions and answers."

doc = Document()
doc.add_heading("Q&A Generated by RAG System", 0)

# Loop through each pair and add to the document
for user, bot in zip(user_msgs, bot_msgs):
    question_text = user.get_text(strip=True).replace("You:", "").strip()
    answer_text = bot.get_text(strip=True).replace("Answer:", "").strip()
    
    doc.add_paragraph(f"Question: {question_text}", style='List Bullet')
    doc.add_paragraph(f"Answer: {answer_text}", style='List Bullet')
    doc.add_paragraph("")  

doc.save("final_output.docx")
